"""
prompt_builder.py
Builds LLM prompts for the two experimental conditions:
  C1 — table only
  C2 — table + metadata
"""

import sys
from pathlib import Path
import pandas as pd
from typing import Optional

# Allow imports from current directory
sys.path.insert(0, str(Path(__file__).parent))
from metadata import extract_metadata, metadata_to_text


SYSTEM_PROMPT = """You are a data scientist with deep expertise in tabular data generation and statistical analysis.

Your task is to determine whether a given dataset is REAL (collected from actual observations or events) or SYNTHETIC (artificially generated by a statistical or machine learning model such as CTGAN, TVAE, GaussianCopula, or similar).

You must:
1. Carefully examine the data presented to you.
2. Look for statistical artifacts, implausible value combinations, suspicious regularities, distribution anomalies, or semantic inconsistencies.
3. Provide a structured verdict with reasoning.

Respond ONLY in the following JSON format:
{
  "verdict": "REAL" or "SYNTHETIC",
  "confidence": <integer 0-100>,
  "reasoning": "<detailed explanation of your decision, referencing specific observations>",
  "red_flags": ["<list of specific suspicious patterns you noticed, if any>"],
  "supporting_evidence": ["<list of patterns that suggest realness, if any>"]
}
"""

CONDITION_1_TEMPLATE = """Below is a tabular dataset in Markdown format. Carefully examine it and determine whether it is REAL or SYNTHETIC.

--- TABLE (first {n_rows} rows shown out of {n_total}) ---
{table_str}

**Dataset Info:**
- Total rows: {n_total}
- Total columns: {n_cols}
- Columns: {col_names}
"""

CONDITION_2_TEMPLATE = """Below is a tabular dataset in Markdown format along with statistical metadata. Carefully examine both and determine whether it is REAL or SYNTHETIC.

--- TABLE (first {n_rows} rows shown out of {n_total}) ---
{table_str}

--- STATISTICAL METADATA ---
{metadata_str}

**Dataset Info:**
- Total rows: {n_total}
- Total columns: {n_cols}
"""


def build_prompt_c1(
    df: pd.DataFrame,
    n_rows_shown: int = 20,
) -> tuple[str, str]:
    """
    Condition 1: Table only (Markdown format with sampling).
    Returns (system_prompt, user_prompt).
    """
    # Sample rows for readability
    if len(df) > n_rows_shown:
        sample = df.sample(n=n_rows_shown, random_state=42).sort_index()
    else:
        sample = df
    
    # Convert to markdown table
    table_str = sample.to_markdown(index=False)

    user_prompt = CONDITION_1_TEMPLATE.format(
        n_rows=len(sample),
        n_total=len(df),
        table_str=table_str,
        n_cols=df.shape[1],
        col_names=", ".join(df.columns.tolist()),
    )
    return SYSTEM_PROMPT, user_prompt


def build_prompt_c2(
    df: pd.DataFrame,
    n_rows_shown: int = 20,
    label: str = "unknown",
) -> tuple[str, str]:
    """
    Condition 2: Table + metadata (Markdown format with sampling).
    Returns (system_prompt, user_prompt).
    """
    # Sample rows for readability
    if len(df) > n_rows_shown:
        sample = df.sample(n=n_rows_shown, random_state=42).sort_index()
    else:
        sample = df
    
    # Convert to markdown table
    table_str = sample.to_markdown(index=False)
    meta = extract_metadata(df, label=label)
    metadata_str = metadata_to_text(meta)

    user_prompt = CONDITION_2_TEMPLATE.format(
        n_rows=len(sample),
        n_total=len(df),
        table_str=table_str,
        n_cols=df.shape[1],
        metadata_str=metadata_str,
    )
    return SYSTEM_PROMPT, user_prompt
